version: '3'
services:
  queueservice:
    build:
      context: ./ # Path to your project directory
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Map container's port 8080 to host's port 8080
    depends_on:
      - rabbitmq
    networks:
      - my-network

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672" # RabbitMQ messaging port
      - "15672:15672" # RabbitMQ management UI
    networks:
      - my-network

networks:
  my-network:
